linters:
  enable:
  - asciicheck
  - bodyclose
  - cyclop
  - deadcode
  - depguard
  - dogsled
  - dupl
  - durationcheck
  - errcheck
  - errname
  - errorlint
  - exhaustive
  - exhaustivestruct
  - exportloopref
  - forbidigo
  - forcetypeassert
  - funlen
  - gci
  - gochecknoinits
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godot
  - godox
  - goerr113
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - ifshort
  - importas
  - ineffassign
  - makezero
  - misspell
  - nakedret
  - nestif
  - nilerr
  - noctx
  - nolintlint
  - prealloc
  - predeclared
  - promlinter
  - revive
  - rowserrcheck
  - sqlclosecheck
  - staticcheck
  - structcheck
  - stylecheck
  - tagliatelle
  - testpackage
  - thelper
  - tparallel
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - wastedassign
  - whitespace
  - wrapcheck
  disable:
  - gochecknoglobals
  - gomnd
  - lll
  - nlreturn
  - paralleltest
  - wsl

linters-settings:
  goimports:
    local-prefixes: github.com/twpayne/go-polyline

issues:
  exclude-rules:
  - linters:
    - scopelint
    path: "_test\\.go"
